version: '3.7'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: realtime
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000

  api:
    image: node:10.15
    hostname: api
    links:
      - mysql
    ports:
      - '3002:3002'
      - '9229:9229'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/server
    command: 'yarn start'

  client:
    image: node:10.15
    hostname: client
    ports:
      - '3003:3003'
    volumes:
      - ../:/usr/src/service
    working_dir: /usr/src/service/client
    command: yarn start

  adminer:
    image: adminer
    ports:
      - 8080:8080